{
 "title": "Ecowitt Weather Station",
 "description": "Ecowitt exporter",
 "tags": [
  "weather",
  "ecowitt"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Now", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_temp{sensor=\"outdoor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_humidity{container=\"ecowitt-exporter\", sensor=\"outdoor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_barom{container=\"ecowitt-exporter\", sensor=\"relative\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_windspeed{container=\"ecowitt-exporter\", sensor=\"windspeed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rainfall",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mm/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_rain{container=\"ecowitt-exporter\", sensor=\"rate\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sunlight",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_solarradiation{container=\"ecowitt-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "High temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "ecowitt_temp{container=\"ecowitt-exporter\", sensor=\"outdoor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Low temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "ecowitt_temp{container=\"ecowitt-exporter\", sensor=\"outdoor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max wind",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "ecowitt_windspeed{container=\"ecowitt-exporter\", sensor=\"windspeed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max wind gust",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "ecowitt_windspeed{container=\"ecowitt-exporter\", sensor=\"windgust\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Current alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 } },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Air temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ecowitt_temp{sensor=\"outdoor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relative humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ecowitt_humidity{container=\"ecowitt-exporter\", sensor=\"outdoor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Barometric pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "ecowitt_barom{sensor=\"relative\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Rainfall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Rainfall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "ecowitt_rain{container=\"ecowitt-exporter\", sensor!~\"total|yearly\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Totals",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_rain{sensor=~\"daily|event|monthly|weekly|yearly|total\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Wind", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Wind speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "expr": "ecowitt_windspeed{container=\"ecowitt-exporter\", sensor!=\"maxdailygust\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Beaufort",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_windspeed_beaufort{container=\"ecowitt-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "ecowitt_winddir{container=\"ecowitt-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_winddir{container=\"ecowitt-exporter\"}"
    }
   ]
  },
  { "title": "Sun", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "UV index",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_uv{container=\"ecowitt-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solar irradiation",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 52 },
   "targets": [
    {
     "expr": "ecowitt_solarradiation{container=\"ecowitt-exporter\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Lightning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Last strike distance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecowitt_lightning", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Closest strike distance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min(ecowitt_lightning{container=\"ecowitt-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecowitt_lightning_num", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last strike",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_lightning_time{container=\"ecowitt-exporter\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Air quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "PM2.5",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "ecowitt_pm25{container=\"ecowitt-exporter\", series=\"realtime\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PM2.5 24-hour average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "ecowitt_pm25{container=\"ecowitt-exporter\", series=\"avg_24h\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UK Air Quality Index",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_aqi{container=\"ecowitt-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Soil moisture", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Soil moisture",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ecowitt_soilmoisture{container=\"ecowitt-exporter\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Battery status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Battery status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_batterystatus{container=\"ecowitt-exporter\"}",
     "legendFormat": "{{sensor}}"
    },
    {
     "expr": "ecowitt_batterylevel{container=\"ecowitt-exporter\"}",
     "legendFormat": "{{sensor}}"
    },
    { "expr": "ecowitt_batteryvoltage", "legendFormat": "{{sensor}}" }
   ]
  }
 ]
}